### ISSUE TITLE
When dragging folders or multi-image formats (.ico) it does not change the number of exif data

### ISSUE THREAD

**Issue by Team-Watchman** [szTheory/exifcleaner#100]
This app broke with the latest update (3.4), the files do not clean as in the previous version that I used, which I have now reinstalled (3.1). The app appears to be functioning normally, but the number of exifs remain unchanged after they are processed. Whether this is the actual case, that the exif information was indeed left untouched, or not, I am unsure as I did not test that possibility.

Windows 10 2004 update, Dell e7440. let me know if you need any further information. Thanks for the app.

**Comment by szTheory** [comment]
Thanks for the report! Some more details that will help:

- Are the remaining exifs sensitive? Sometimes `exiftool` (what ExifCleaner uses under the hood) does not remove all meta data because they are part of the file format itself.
- If you run the file through the [`exiftool` command line program](https://exiftool.org/) manually, does that remove the exif data?
- Can you provide an example of a file that you tried to process, and it didn't work? And/or a screenshot of the before/after?
- Does 3.1 remove exif for the same file, while 3.4 doesn't?
- When you open the chrome developer tools within the app (Electron provides this, I believe it's Edit -> Developer Tools or something similar on Windows) and go to the Console tab, do you see errors? If so can you include a screenshot of them here or copy and paste them?

**Comment by Team-Watchman** [comment]
Hello szTheory, those are a lot of questions :). I hope to get around to testing all those many requests sooner or later, I am beat ATM, however :(. I can say this, that apparently the older version also behaves the same, I just did not trigger the phenomena, apparently. It seems to occur, upon cursory observation, when I drop a whole file on the app window which is full of various formats. The formats that I usually work with are: .jpg, .png, .ico, .webm, and .gif. I suspect the problem could be the multi-page/image properties of multi-resolution icons and multiple image .gif files. Let me know what you think about this hip-shot theory. 
Again, thanks for your work,
Team-Watchman

**Comment by szTheory** [comment]
Thanks let me know what you find. It could be a problem with multi-image .ico like you mentioned.

But the main issue might be that you are dragging a folder onto ExifCleaner instead of going into the folder and dragging all the files in. I probably have to add more robust support for dragging folders in and then recursively processing their contents, since other users have reported similar problems and I didn't test that usage pattern when developing the app.

Can you experiment with dragging files in directly versus dragging the whole folder in, and let me know how that goes as well? I'm pretty busy so it might take me a bit to get around to testing it all and updating the app on my end.

**Comment by Team-Watchman** [comment]
Hello szTheory,
Yes, I can do that the next time I clean some files before uploading them to Discord, or elsewhere. 
I will let you know when I get around to this. Sorry for the late reply, as I have a lot of irons in the fire at this time.
Thanks for your time,
Team-Watchman.

**Comment by szTheory** [comment]
No rush. Have a good weekend :)

**Comment by Team-Watchman** [comment]
szTheory, thanks and you as well.
Here are a couple of screenshots from dragging files instead of folders.
Team-Watchman
![TEST2](https://user-images.githubusercontent.com/63068185/97106547-675a3980-1690-11eb-84dd-eaaca6ab4585.JPG)
![TEST1](https://user-images.githubusercontent.com/63068185/97106548-67f2d000-1690-11eb-8729-1defcf39e03d.JPG)

**Comment by szTheory** [comment]
It looks to me like the exif are being cleaned. For some files, there is a minimum baseline of information that `exiftool` returns because it's about the image format itself, and not something that can be erased. Maybe I should change the flags that are passed to `exiftool` to not report that info so that it's less confusing. However, I see "Software: Google" on one of the files you have highlighted and that seems like something that should have been erased. You could try dragging the same file in multiple times to see if that fixes it, and it would help narrow down the possibility of what is happening. Also if you go into dev tools you can check the console tab and see if there are any errors.

**Comment by Team-Watchman** [comment]
szTheory,
Okay, I will remember to do just those things next time I need to clean a batch of files. Thanks for your time and interest, and thanks for your work.
Team-Watchman

**Comment by szTheory** [comment]
Closing this for now. Just let me know if you run into more problems or get more info to troubleshoot issues you are seeing and we can reopen it.

**Comment by Team-Watchman** [comment]
szTheroy, okay.  I guess there wasn't much of an issue after all, just a misunderstanding on my part of the nature of image formats and exif information. Thanks for your free app and I would like to say that it is very nicely done. 

On another note, I was wondering if you would consider, sometime in the future, of adding functionality for dropping files on the application's shortcut to automatically load the image/s into the app or possibly automaticallay running a preset course. That is, if you think a feature like this would be beneficial to others.

Again, thanks for your time and excellent work. Props.
Team-Watchman

**Comment by szTheory** [comment]
Thanks! I wanted to add the ability to drag and drop it to the ExifCleaner icon in your taskbar/dock, but Electron doesn't seem to support that in their API right now. I want to keep the app as simple as possible to cover the 90% use case, so I probably won't add something like automatically running on a preset course. But if someone wanted to make a separate spinoff version of ExifCleaner with more features for power users I'd be glad to see that.

**Comment by Team-Watchman** [comment]
Oh, interesting that you wanted to implement that. See you around, SZ! :D 

![Context_Menu](https://user-images.githubusercontent.com/63068185/97649118-848e5f80-1a24-11eb-94fa-72d875bf2d73.JPG)
