### ISSUE TITLE
Advice needed.. 

### ISSUE THREAD

**Issue by rsyncOSX** [szTheory/exifcleaner#102]
Hi.. I am developing RsyncOSX, a macOS GUI for rsync.. I am in process of starting a project to develop a cross plattform by utilizing TypeScript, electron, React version of RsyncOSX (as your exifcleaner app).. I dont have any experience in Javascript development - do you have any suggestions where to start learning ???

**Comment by szTheory** [comment]
Hi, your Rsync app looks pretty sweet!

The best single JavaScript book is [JavaScript for Web Developers](https://www.wiley.com/en-us/Professional+JavaScript+for+Web+Developers%2C+4th+Edition-p-9781119366577). It's a complete reference. Whereas most books only cover the language, this also covers all of the DOM and browser APIs. [Programming TypeScript](https://www.oreilly.com/library/view/programming-typescript/9781492037644/) is a good intro to TS, and check out [Effective TypeScript](https://www.oreilly.com/library/view/effective-typescript/9781492053736/) and [Effective JavaScript](https://www.oreilly.com/library/view/effective-javascript-68/9780132902281/) for an advanced treatment on the languages. One thing that tripped me up at first is the difference between the Node runtime and JS in the browser, and [Learning Node](https://www.oreilly.com/library/view/learning-node-2nd/9781491943113/) cleared that up for me. The only good Electron book is [Electron in Action](https://www.manning.com/books/electron-in-action). That's a lot of books, but I find the information higher quality and more consistent than trying to learn from piecemeal blogs.

The JS package landscape on NPM is huge and there's some good stuff but the quality is really bad overall. There's a culture of deep and wide dependency trees and pulling in packages that only have one trivial function like reversing a string or something. So when looking at an open source project now the first thing I check out is their package.json and package-lock.json. A lot of the time you can just look at their code and copy/paste the one part you need instead of including it as a dependency. I'm still in the process of ripping out a bunch of garbage that I had originally pulled into ExifCleaner when learning JS/Electron. For example this is in my `package.json`

```json
	"dependencies": {
		"node-exiftool": "^2.3.0",
		"source-map-support": "^0.5.19",
		"spectre.css": "^0.5.8"
	},
	"devDependencies": {
		"@types/node": "^12.0.0",
		"electron": "^10.0.0",
		"electron-builder": "^22.8.0",
		"electron-webpack": "^2.8.2",
		"electron-webpack-ts": "^4.0.1",
		"node-sass": "^4.13.1",
		"prettier": "2.0.5",
		"sass-loader": "^10.0.0",
		"typescript": "^3.8.3",
		"webpack": "^4.41.2"
	},
```

and it results in a [7700 line lock file](https://github.com/szTheory/exifcleaner/blob/master/yarn.lock). Granted, most of that dependency tree is in development only but it gives you an idea of how quickly it can get out of hand. There's just no way a single person or team can audit that many dependencies so you are basically running mystery code on your computer with the node interpreter.

Also note that ExifCleaner doesn't use React, just basic DOM manipulation instead. But my app is a lot simpler than yours so I could get away with that. Hope that helps!

**Comment by rsyncOSX** [comment]
Hi and thank you very much for your advices.. I will follow your links and advices and take it from there... I will also use your exifcleaner as sample and learn how it is build.. I am closing this issue now, I have a copy of your answer.. And again, thx for replying...

All the best,
Thomas
