### ISSUE TITLE
Windows file path metadata is not being removed

### ISSUE THREAD

**Issue by deanWpennington** [szTheory/exifcleaner#108]
No tool I have tried, including this one removes the file path which includes the name of my PC to windows and my name which is the user ID also in windows  otherwise known in an EXIF as owner & Computer. Does any tool eliminate these?

---

ExifCleaner 3.4.0
Electron 10.1.2
win32 10.0.18363
Locale: en-US

**Comment by szTheory** [comment]
Maybe it's filesystem metadata rather than image metadata. For example on a Mac there is Spotlight metadata that requires a separate process to to remove as reported [in this issue](https://github.com/szTheory/exifcleaner/issues/86). You can test it out by installing the stand-alone exiftool program (which ExifCleaner is based on) from https://exiftool.org/ and then running `exiftool my_image_here.jpg` and check the results. If exiftool can't detect that metadata, but your Windows file explorer does, it's probably filesystem metadata.

Can you upload example file here, possibly from another user account on your computer or from within a virtual machine? And if possible a screenshot of where on your operating system's interface it's displaying the data that isn't being eliminated (like in the Mac issue linked above). I am considering adding support for removal of filesystem metadata to ExifCleaner, so this will be helpful to track it down and figure out a reproducable process for removing the data.

**Comment by szTheory** [comment]
I'm going to close this for now until we can get more information
