### ISSUE TITLE
Confirm before clear

### ISSUE THREAD

**Issue by Bellisario** [szTheory/exifcleaner#143]
Can be useful to implement a dialog or something that asks the user if wants to clear all metadata and shows currents.

**Comment by szTheory** [comment]
I like your idea, but I'm trying to keep the app very simple with the idea being that you want to get rid of all the metadata immediately, so that it can be used in a daily workflow with only 1 step. For more power-user use cases like just viewing metadata people should look to other apps like `exiftool` itself from the command line, or a GUI.
