### ISSUE TITLE
Error when trying to delete metadata from images (Linux .deb install and AppImage)

### ISSUE THREAD

**Issue by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [szTheory/exifcleaner#15]
This is the error:

Unhandled Promise Rejection
Error: Exiftool process is not open
    at ExiftoolProcess.close (/opt/ExifCleaner/resources/app.asar/node_modules/node-exiftool/src/index.js:33:35)
    at file:///opt/ExifCleaner/resources/app.asar/webpack:/src/common/add_files.js:23:6
    at file:///opt/ExifCleaner/resources/app.asar/webpack:/src/common/add_files.js:22:8

**Comment by szTheory** [comment]
Thanks for the feedback, I'll look into it. In the meantime can you tell me what operating system and version of the operating system you are running? Also, what specific action were you doing when the error occurred? For example, did you drag in a single image, or was it multiple and if so how many. And what was the file type?

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
What an asshole, I forgot to add details. I'm using Debian 10 stable. I dragged a single image and it was JEPG.  It happens every time, I downloaded today and it didn't work, do you know if it could be a problem with my PC?

**Comment by szTheory** [comment]
Oh you know what, perhaps it's from this part of the install instructions from the README (which I could make more prominent).
`For Linux, The AppImage needs to be made executable after download.`

If that doesn't fix it I'll set up a Linux VM to test. I have to admit I haven't tested it on Linux myself yet. I thought I had at least one Linux user that was using it with success, so I've relied on that until now.

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
I've installed it with the .deb because or either there's something wrong with my machine or or I don't know how to install tarballs, because once I move them to the /usr/share/applications I can't find a way to create a desktop shortcut. So I don't know if the README applies here.

**Comment by szTheory** [comment]
OK thanks. I'm sorry to say it might take me a little while to get around to this because I haven't used Debian before, but I will certainly research how to get the environment set up and install. I seem to remember hearing something about being able to install .deb on Ubuntu.

Anyways, I suspect this is an issue with the `exiftool` binary not having executable permission. So if you can navigate within the application directoy and find that binary then flip the permission it might work. If you can get it working let me know what instructions you used and I can add it to the README and credit you in the README as well if you wish.

**Comment by totoroot** [comment]
Just wanted to add that the AppImage didn't work for me on the following system after installation:
OS: Ubuntu 18.04.4 LTS x86_64
Kernel: 4.15.0-91-generic

I looked if I even had exiftool installed and it wasn't, but the error persisted even after installation. exiftool however is executable from the command line as a user without superuser privileges so I'm not quite sure what the problem is...

**Comment by Scopuli** [comment]
I just got the same error with the AppImage. 

PopOS 19.10
exiftool is installed

Unhandled Promise Rejection
Error: Exiftool process is not open
    at ExiftoolProcess.close (/tmp/.mount_ExifClGgiRKm/resources/app.asar/node_modules/node-exiftool/src/index.js:33:35)
    at file:///tmp/.mount_ExifClGgiRKm/resources/app.asar/webpack:/src/common/add_files.js:23:6
    at file:///tmp/.mount_ExifClGgiRKm/resources/app.asar/webpack:/src/common/add_files.js:22:8

**Comment by szTheory** [comment]
Thanks everyone. I'll have to set up a Linux install to get this ironed out. It might take me a bit though, I'm sorry.

**Comment by szTheory** [comment]
@5a384507-18ce-417c-bb55-d4dfcc8883fe @Scopuli @totoroot I set up an Ubuntu install and fixed this at least with the AppImage version (didn't test the .deb yet but I suspect it will work now). Let me know if you are still having issues

**Comment by totoroot** [comment]
Tried both and it works! Congrats and thanks :clap: 
There is no icon yet for the .deb version but I've seen you're aware of this issue and it does not really bother me as I will stick to the AppImage
Maybe a confirmation dialogue, at least if more than one file will be processed, would be good. This way it would be easier to avoid deleting metadata of images by accident. Coming to think of it, adding a directory to remove all metadata of all files inside would be convenient too.
Anyways, good job on this :+1:

**Comment by Scopuli** [comment]
Using AppImage, works perfectly.
