### ISSUE TITLE
Error: Exiftool process is not open

### ISSUE THREAD

**Issue by Kali273** [szTheory/exifcleaner#151]
Cleaner always work normal but today open it and cleaner not working. I tried download latest version setup and exe. 
Drag and drop neither Open file not working.. Cleaner do nothing after drop file or open..

**Comment by szTheory** [comment]
Thanks for the report. Can you open the developer tools and see if there are any errors, then copy/paste the message or upload a screenshot? If it was working but stopped for seemingly no reason, you might also want to try restarting your computer. I don't see any reason why you should have to, but sometimes restarting helps random failure states in any computer system.

**Comment by Kali273** [comment]
![er](https://user-images.githubusercontent.com/76413175/120105028-94575900-c157-11eb-86e3-7f987b4a6fbb.png)

**Comment by szTheory** [comment]
Thanks, I've seen this happen on Windows before. Not sure what the issue is exactly. Maybe the exiftool process is taking too long to start up before you drag and drop the files. Can you try dragging the files on again, after the first time that doesn't work? That might give it time to spin up the exiftool procss if it's taking too long. Not a permanent fix but a potential workaround.

**Comment by Kali273** [comment]
Restart pc, reinstal, waiting .. nothing work

**Comment by Kali273** [comment]
I finally solved it... Tried all repairs, sfc scan etc. but finally only [This](http://revertservice.com/10/null/) restore helped me.  Cleaner works again :)

**Comment by szTheory** [comment]
Oh great to hear! For anyone searching this you want the Null Service Defaults in Windows 10 from the link @Kali273 posted above.
