### ISSUE TITLE
Editing Metadata

### ISSUE THREAD

**Issue by Loki-L1130** [szTheory/exifcleaner#163]
When Clearing Metadata how about making it editable instead of cleaning up ?

I actually mean Edit Option in the File Tab to edit things.

**Comment by szTheory** [comment]
Thanks for the suggestion! After thinking on it, I'm going to leave those more advanced use cases to `exiftool` from the command-line, or other power user GUI tools.

**Comment by Loki-L1130** [comment]
I recently searched about GUI-Based Exiftool and got to know about [jExifGUI](https://github.com/hvdwolf/jExifToolGUI) which is actually great than CLI based original Exiftool. 

GUI has dependency on CLI for operating. But If forked and implemented on ExifCleaner would be great. But it will take a lot of Time and Resources. So, As you said the GUI-Based exiftool is great though.

So, I think that you might recommend it as a Sidenote about jExiftoolGUI which will helpful for orher users coming to & in search of one. 

I would like to open a New Issue. But, Instead of bloating the Issue Page of this Repository, I am asking it here : I tried to remove all Metadata for .MKV Video File in GUI based exiftool but it showed that it is not currently supported in exiftool. And when tried in exifcleaner it shows the same amount of Metadata. 

So, Is Exifcleaner based Totally on exiftool ?

Which tells me that Removing Metadata for FIles is separated from exiftool and Forked into GUI based App while GUI based exiftool does both Editing and Removing.

I am just getting up the Idea and not ranting or discouraging the Project.

**Comment by szTheory** [comment]
Thanks for the feedback. It looks like jExifGUI is similar to ExifCleaner in that it's a GUI on top of exiftool, although jExifGUI probably has more features. I can't really recommend other GUI tools in the README since I don't have experience with them to say one way or another. And there are plenty of websites where you can find alternatives such as [this site](https://alternativeto.net/software/exifcleaner-by-sztheory/). But at least people might find your recommendation by searching the Issues page.

To answer your question, yes ExifCleaner is based totally on the command-line tool `exiftool`. On the exiftool website, it shows that mkv only supports read of mkv files, not write (which is needed to clear the exif data). That's why I didn't list mkv on the ExifCleaner readme. However as `exiftool` adds support for more file types, it will become available in future versions of ExifCleaner that include the updated `exiftool`. Hope that makes sense.
