### ISSUE TITLE
Recursively process sub-folders

### ISSUE THREAD

**Issue by LukasThyWalls** [szTheory/exifcleaner#18]
Hi

Now, when you add a folder, and there is some files and some folder, exifcleaner only process the files. To process every sub-folder you need to add all of them one by one manually, and if there are sub-sub-folders add them manually, etc.

I think it should be useful if you add a folder, exifcleaner process all the files, and then automatically add all the sub-folders and try to process them. Also making an option to opt-in/opt-out this feature, and maybe should be some kind of measure to avoid loops (or a way to make stop the file process).

Thanks in advance.

**Comment by szTheory** [comment]
Great idea! I think it would be a good default to process all sub-folders, so I'll add that feature.

I don't want to add an option though, only because I want to avoid feature bloat. The scope of this project that I am targeting is daily use for people who want privacy, not for power users. I would definitely support anyone who wants to fork the project to add a bunch of extra features and settings though.

I also like your idea of adding a stop button. However I'm thinking that instead, I will just add a popup if you have more than say 10 files. It will say "You are about to process 2,313 files. Are you sure?". That will be a lot simpler to code and not require a change to the interface.

**Comment by LukasThyWalls** [comment]
The main issue with that is i don't know how you think your app should be dealing when you add a folder with subfolders, it will check the files and then add the subfolders to check their files, and the sub-subfolders...? it will check the files and process them, and then add the subfolders to check and process, and so on?

I'm asking that because with the first case you can have a loop or a lot of files, and you can control the number of files and "stop" or show a message if there are a lot, but any file is processed. With the second you can number the files processed, but you don't know the total number until it ends or reach a selected number, but there will be an amount of files processed and other their aren't and you will not know what are each ones.

So pointing that out, should be cool if:
- You enter some kind of measure to not to follow symlinks when are adding recursively folders, to avoid loops (for some people could be a down, but if it's needed you can rethink that later)
- A proccesed files number or a processed/total files number stat (depending the way they count)
- Instead of show only the added folder in the gui, auto-add the subfolders below (if there are), showing the EXIF number if there are files procesed in that folder, and showing nothing if there aren't (but could have subfolders with files in that folder). With this you can see what is doing the app at any time in a big folder tree. Something like:
```
Folder
-Folder/Subfolder1
--Folder/Subfolder1/SubSubfolder
-Folder/Subfolder2
...
```
- The Stop button should be useful, in addition with the last point, because you can check where you the stopped the process, instead of closing the window losing that information.

The third point maybe is the worse one, because you want to keep the app simple. But it could be a great addition and now we are only talking.

**Comment by szTheory** [comment]
Really good points here. I'll have to think about it and maybe come back to you with some UI mockups.
