### ISSUE TITLE
error on startup

### ISSUE THREAD

**Issue by amnesia1984** [szTheory/exifcleaner#85]
Unhandled Promise Rejection
Error: Image could not be created from /opt/ExifCleaner/exifcleaner.png
    at createMainWindow (/opt/ExifCleaner/resources/app.asar/webpack:/src/main/window_setup.ts:74:9)
    at setup (/opt/ExifCleaner/resources/app.asar/webpack:/src/main/index.ts:23:14)

5.8.6-1-MANJARO #1 SMP PREEMPT Thu Sep 3 14:19:36 UTC 2020 x86_64 GNU/Linux
KDE

installed through add remove software

**Comment by szTheory** [comment]
Sorry about that! This is the same issue as https://github.com/szTheory/exifcleaner/issues/80. I've got a fix ready but I'm still QA'ing the release. In the meantime you can try the workaround described by others users at that link, or use a previous version of ExifCleaner. I'll let you know when the fix is released.
