### ISSUE TITLE
VirusTotal false positive

### ISSUE THREAD

**Issue by brian6932** [szTheory/exifcleaner#92]
https://www.virustotal.com/gui/file/3bc1c109dcd4d1abdcbdebb35a1d4e5dab0af165fd1108c292d7cb364ed65a0d/detection

**Comment by szTheory** [comment]
Thanks for the report, can you provide more details?
![detect](https://user-images.githubusercontent.com/28652/95809186-b9e53e80-0cfd-11eb-8c67-236b8251122a.png) The only thing I can think of is that the Windows exe is not signed by developer, and some notes on https://exiftool.org/ about the Windows version of exitfool being known to cause problems with some antivirus software. But neither of those seem to apply here. The eGambit warning doesn't seem to point to anything specific, almost looks like a heuristic score. I've never heard of eGambit before but I looked it up and it looks like an Android antivirus software app.

**Comment by brian6932** [comment]
:shrug: idk what it is either

**Comment by szTheory** [comment]
I'm going to close this issue since I don't see anything actionable about it. But at least now if someone searches the issue for "virus" or "false positive" they will come here and can provide more info. The only other thing I can say is make sure you download ExifCleaner from the official Github Releases page https://github.com/szTheory/exifcleaner/releases. If the app is downloaded from other third-party websites, it's always possible they could repackage it with changes including possible viruses. And to be absolutely sure, you can always clone the git repository and build your own copy from source and run that (or run it in dev mode).

Thanks again for the report!

**Comment by papb** [comment]
A similar problem was reported for https://github.com/sindresorhus/ps-list/issues/42 - you can look there for what action they ended up taking about it.
