### ISSUE TITLE
ExifCleaner Helper (Renderer) using lots of resources

### ISSUE THREAD

**Issue by dibbi** [szTheory/exifcleaner#93]
Hi, I checked activities on my mac and a process named "ExifCleaner Helper (Renderer)" is using up lots of ressources. I'm not even running the program. Do you know what is going on?

Kindest

Dibbi

---

ExifCleaner 3.3.1
Electron 9.0.0
darwin 19.6.0
Locale: de

**Comment by szTheory** [comment]
Hi, thanks for the feedback! Is it using a lot of CPU, or memory? If it's memory can you specify how much? And if it's CPU, how much % of CPU is it using?

**Comment by dibbi** [comment]
Sorry I killed the process now and made no screenshot.

It was using up CPU (a lot, like the fan was running all the time, no ram, tho)

**Comment by szTheory** [comment]
Thanks I'll keep an eye out for this. I'm still working on the next release where I made significant changes to the `exiftool` integration that make it a lot more efficient. I think it will fix the problem you are seeing. If you want you can try it out by checking out the master branch and running in dev locally. Otherwise, I'll let you know when the next release is ready.

**Comment by szTheory** [comment]
@dibbi just released the new version if you want to check it out and see if it helps https://github.com/szTheory/exifcleaner/releases/tag/v3.4.0
